name: Run Yahoo Fantasy Script

on:
  schedule:
    # Runs at 8:00 AM UTC (or adjust as needed) every Tuesday
    - cron: '0 8 * * 2'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Adjust to the Python version you need

      # Install dependencies (if required)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the Python script
      - name: Run Yahoo Fantasy script
        run: |
          python player_week_projections.py \
            --yahoo_email ${{ secrets.YAHOO_EMAIL }} \
            --yahoo_pw ${{ secrets.YAHOO_PW }} \
            --yahoo_league_id ${{ secrets.YAHOO_LEAGUE_ID }} \
            --yahoo_league_year ${{ secrets.YAHOO_LEAGUE_YEAR }}
