name: Run Yahoo Fantasy Script

on:
  schedule:
    # Runs at 8:00 AM UTC (or adjust as needed) every Tuesday
    - cron: '0 8 * * 2'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    environment: Jon-prod-approval
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Yahoo Fantasy script
        env:
          YAHOO_EMAIL: ${{ env.YAHOO_EMAIL }}
          YAHOO_PW: ${{ env.YAHOO_PW }}
          YAHOO_LEAGUE_ID: ${{ secrets.YAHOO_LEAGUE_ID }}
        run: |
          python player_week_projections.py \
            --yahoo_email $YAHOO_EMAIL \
            --yahoo_pw $YAHOO_PW \
            --yahoo_league_id $YAHOO_LEAGUE_ID

      - name: Upload CSV files
        uses: actions/upload-artifact@v3
        with:
          name: nfl-results
          path: results/